language: java

sudo: false

jdk:
  - oraclejdk8

install: true

#script:
#  - sudo apt-get update && sudo apt-get install oracle-java8-installer
 # - java -version
  
notifications:
  email:
    - william.shackleford@nist.gov
    - wshackle@gmail.com

# Change this to your needs
#script: ./configure && make && make check && cd rcsjava_maven/rcslib && mvn -version && mvn -e compile &&  mvn test && mvn verify 

